# 1. Introducción
La generación de variables se desarrolló inicialmente de forma manual en pandas utilizando un subconjunto del dataset en el notebook `03_feature_engineering_manual.ipynb`, con el objetivo de validar la lógica de cálculo y el comportamiento temporal de las series.
En este notebook se replica el mismo proceso utilizando funciones reutilizables definidas en `feature_engineering.py`, que se ejecutan sobre el dataset de muestra junto con validaciones básicas (`validate.py`).<br>
Debido al volumen del dataset completo, el pipeline final se implementó en Apache Spark, permitiendo ejecutar las transformaciones sobre todos los datos mediante procesamiento distribuido.

# 2. Carga del dataset sample

In [1]:
import os
import sys
import pandas as pd

PROJECT_ROOT = os.path.abspath("../..")

if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

from src.exploratory.feature_engineering import (
    generate_features_from_df
)

# Cargar sample
df = pd.read_parquet(
    "../../data/processed/exploratory/m5_clean_sample.parquet"
)

print("Input shape:", df.shape)

# Generar features usando script feature_engineering.py
df_features = generate_features_from_df(df)

print("Output shape:", df_features.shape)

df_features.head()

Input shape: (95650, 22)
Output shape: (95650, 31)

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,sell_price,lag_1,lag_7,lag_28,rolling_mean_7,rolling_std_7,rolling_mean_28,rolling_std_28,rolling_mean_56,rolling_std_56
0,HOBBIES_1_100_CA_1_validation,27,3,1,0,0,d_1,1,2011-01-29,11101,...,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HOBBIES_1_287_CA_1_validation,30,3,1,0,0,d_1,0,2011-01-29,11101,...,5.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HOUSEHOLD_1_202_CA_1_validation,37,5,2,0,0,d_1,0,2011-01-29,11101,...,1.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HOUSEHOLD_1_537_CA_1_validation,41,5,2,0,0,d_1,3,2011-01-29,11101,...,15.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FOODS_2_382_CA_1_validation,7,1,0,0,0,d_1,2,2011-01-29,11101,...,3.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 4. Validaciones básicas con script evaluation.py

In [2]:
# Validar dataset generado
from src.exploratory.validate import validate_features

validate_features(df_features)

df_features.head()

----- VALIDATION START -----
Shape: (95650, 31)
Column validation OK

Top missing columns:
event_type_2       0.997909
event_name_2       0.997909
event_type_1       0.919498
event_name_1       0.919498
lag_28             0.014637
lag_7              0.003659
rolling_mean_56    0.001098
rolling_std_56     0.001098
rolling_std_28     0.000805
rolling_mean_28    0.000805
dtype: float64

----- VALIDATION OK -----

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,sell_price,lag_1,lag_7,lag_28,rolling_mean_7,rolling_std_7,rolling_mean_28,rolling_std_28,rolling_mean_56,rolling_std_56
0,HOBBIES_1_100_CA_1_validation,27,3,1,0,0,d_1,1,2011-01-29,11101,...,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HOBBIES_1_287_CA_1_validation,30,3,1,0,0,d_1,0,2011-01-29,11101,...,5.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HOUSEHOLD_1_202_CA_1_validation,37,5,2,0,0,d_1,0,2011-01-29,11101,...,1.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HOUSEHOLD_1_537_CA_1_validation,41,5,2,0,0,d_1,3,2011-01-29,11101,...,15.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FOODS_2_382_CA_1_validation,7,1,0,0,0,d_1,2,2011-01-29,11101,...,3.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN